In [2]:
import numpy as np
w = [1, 4, 3, 1]  
p = [1500, 3000, 2000, 2000]   
m = 4 
def dynamic(w,p,W):
    n=len(w)
    # 定义i行j列矩阵，表示容量i下前j个物品能装的最大价值
    dp=np.zeros((n+1,n+1))
    for i in range(1,n+1):
        for j in range(1,n+1):
            if i>=w[j-1]:
                dp[i,j]=max(dp[i,j-1],dp[i-w[j-1],j-1]+p[j-1])
            else:
                dp[i,j]=dp[i,j-1]
    return dp     
dp=dynamic(w,p,m)
# error:索引为负时记录前面数据未报错
print(dp)

[[   0.    0.    0.    0.    0.]
 [   0. 1500. 1500. 1500. 2000.]
 [   0. 1500. 1500. 1500. 3500.]
 [   0. 1500. 1500. 2000. 3500.]
 [   0. 1500. 3000. 3500. 4000.]]


In [20]:
#扔鸡蛋问题，100层楼有两个鸡蛋，求为找到恰好鸡蛋扔碎掉的楼层数的最小测试次数
n,m=100,2
def drop(n,m):
    #定义n层楼m个鸡蛋情况下，最小测试次数矩阵
    dp=np.zeros((n+1,m+1))
    dp[:,1]=[i for i in range(n+1)]
    dp[1,:]=1
    for i in range(1,n+1):
        for j in range(2,m+1):
            min_i=100       
            for k in range(1,i+1):
                now_k=1+max(dp[i-k,j],dp[k-1,j-1])
                if now_k<min_i:
                    min_i=now_k
            dp[i,j]=min_i
    return dp
print(drop(100,2)[100,2])
             

14.0


In [3]:
a=np.zeros((3,3))
a[:,1]=[i for i in range(3)]

In [4]:
a

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 2., 0.]])

In [6]:
list(range(2,3))

[2]

In [24]:
5^3

6