In [2]:
import numpy as np
w = [1, 4, 3, 1]  
p = [1500, 3000, 2000, 2000]   
m = 4 
def dynamic(w,p,W):
    n=len(w)
    # 定义i行j列矩阵，表示容量i下前j个物品能装的最大价值
    dp=np.zeros((n+1,n+1))
    for i in range(1,n+1):
        for j in range(1,n+1):
            if i>=w[j-1]:
                dp[i,j]=max(dp[i,j-1],dp[i-w[j-1],j-1]+p[j-1])
            else:
                dp[i,j]=dp[i,j-1]
    return dp     
dp=dynamic(w,p,m)
# error:索引为负时记录前面数据未报错
print(dp)

[[   0.    0.    0.    0.    0.]
 [   0. 1500. 1500. 1500. 2000.]
 [   0. 1500. 1500. 1500. 3500.]
 [   0. 1500. 1500. 2000. 3500.]
 [   0. 1500. 3000. 3500. 4000.]]


In [20]:
#扔鸡蛋问题，100层楼有两个鸡蛋，求为找到恰好鸡蛋扔碎掉的楼层数的最小测试次数
n,m=100,2
def drop(n,m):
    #定义n层楼m个鸡蛋情况下，最小测试次数矩阵
    dp=np.zeros((n+1,m+1))
    dp[:,1]=[i for i in range(n+1)]
    dp[1,:]=1
    for i in range(1,n+1):
        for j in range(2,m+1):
            min_i=100       
            for k in range(1,i+1):
                now_k=1+max(dp[i-k,j],dp[k-1,j-1])
                if now_k<min_i:
                    min_i=now_k
            dp[i,j]=min_i
    return dp
print(drop(100,2)[100,2])
             

14.0


In [3]:
a=np.zeros((3,3))
a[:,1]=[i for i in range(3)]

In [4]:
a

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 2., 0.]])

In [6]:
list(range(2,3))

[2]

In [24]:
5^3

6

In [17]:
# 矩阵连乘问题
import numpy as np
p=[30, 35, 15, 5, 10, 20, 25]
def matrixchain(p):
    n=len(p)-1
    matmul=np.zeros((n,n))
    record=np.zeros((n,n),dtype='int32')
    for i in range(n-1,-1,-1):
        for j in range(i+1,n):
            matm=1e9
            rk=0
            for k in range(i,j):                
                matk=p[i]*p[k+1]*p[j+1]
                matk=matmul[i,k]+matmul[k+1,j]+matk
                if matm>matk:
                    matm=matk
                    if k>i and k<j:
                        rk=k
            matmul[i,j]=matm
            record[i,j]=rk
    rlist=[]
    i,j=0,n-1
    kr(record,rlist,i,j)
        
    return matmul,rlist,record
def kr(record,rlist,i,j):
    if i>j+1:
        return None
    kpi=record[i,j]
    if kpi>i and kpi<j:
        rlist.append(kpi)
        kr(record,rlist,i,kpi)
        kr(record,rlist,kpi+1,j)
    return None
print(matrixchain(p))

(array([[    0., 15750.,  7875.,  9375., 11875., 15125.],
       [    0.,     0.,  2625.,  4375.,  7125., 10500.],
       [    0.,     0.,     0.,   750.,  2500.,  5375.],
       [    0.,     0.,     0.,     0.,  1000.,  3500.],
       [    0.,     0.,     0.,     0.,     0.,  5000.],
       [    0.,     0.,     0.,     0.,     0.,     0.]]), [2, 4], array([[0, 0, 0, 2, 2, 2],
       [0, 0, 0, 2, 2, 2],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]]))


In [4]:
list(range(5,0,-1))

[5, 4, 3, 2, 1]

In [18]:
record

NameError: name 'record' is not defined