In [1]:
import numpy as np
array=np.random.permutation(10)

In [4]:
#插入排序
def insert_sort(array):
    n=len(array)
    for j in range(1,n):
        i=j-1
        key=array[j]
        while i>=0 and array[i]>key:
            array[i+1]=array[i]
            i-=1
        array[i+1]=key
    return array

In [5]:
print(array)
print(insert_sort(array))

[8 9 3 4 6 0 5 1 7 2]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
#选择排序
def selection_sort(array):
    n=len(array)
    for i in range(n):
        num=array[i]
        ind=i
        j=i
        while j<n:
            if array[j]<num:
                num=array[j]
                ind=j
            j+=1
        array[ind]=array[i]
        array[i]=num
    return array
array=np.random.permutation(10)
print(array)
print(selection_sort(array))

[1 3 2 5 6 9 4 0 8 7]
[0 1 2 3 4 5 6 7 8 9]


In [31]:
# 合并排序
def merge(arr1,arr2):
    i,j=0,0
    arr1=np.append(arr1,np.inf)
    arr2=np.append(arr2,np.inf)
    n=len(arr1)+len(arr2)-2
    array=[]
    while i+j<n:
        if arr1[i]<arr2[j]:
            array=np.append(array,arr1[i])
            i+=1
        else:
            array=np.append(array,arr2[j])
            j+=1
    return array
arr1=[1,3,5]
arr2=[2,4,6]
print(merge(arr1,arr2))
def merge_sort(array):
    if len(array)<2:
        return array
    mid=round(len(array)/2)
    left=merge_sort(array[0:mid])
    right=merge_sort(array[mid:])
    return merge(left,right)
array=np.random.permutation(10)
print(merge_sort(array))

[1. 2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
# 快速排序
def quick_sort(array):
    if len(array)<2:
        return array
    key=array[0]
    left=[i for i in array[1:] if i<key]
    right=[i for i in array[1:] if i>key]
    return quick_sort(left)+[key]+quick_sort(right)
array=np.random.permutation(10)
quick_sort(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
key=3
[i if i <3 else 3 for i in array ]

[3, 0, 3, 3, 3, 1, 2, 3, 3, 3]

In [39]:
array

array([3, 0, 9, 6, 4, 1, 2, 7, 5, 8])

In [27]:
np.append(b,[0])

array([ 1.,  2.,  3., inf,  0.])